# Generated by Django 2.2.8 on 2020-01-15 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('about', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('percent', models.PositiveSmallIntegerField(default=0, verbose_name='Porcentaje')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, max_length=1000, null=True, upload_to='picture-experience/')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicial')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Final')),
                ('description', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='portfolio.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, max_length=1000, null=True, upload_to='picture-education/')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicial')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Final')),
                ('description', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educaciones', to='portfolio.Profile')),
            ],
        ),
    ]
